MOVIES = [
    {
        "id": 1,
        "title": "Stranger Things",
        "genre": "Sci-Fi",
        "year": 2016,
        "rating": "16+",
        "format": "Series",
        "seasons": 5,
        "episodes": 42,
        "imdb_rating": "8.6",
        "description": "A missing boy, a mysterious girl, and a small town hiding an extraordinary secret.",
    },
    {
        "id": 2,
        "title": "Wednesday",
        "genre": "Mystery",
        "year": 2022,
        "rating": "13+",
        "format": "Series",
        "seasons": 2,
        "episodes": 16,
        "imdb_rating": "8.0",
        "description": "At Nevermore Academy, Wednesday Addams investigates a mystery with her signature dark wit.",
    },
    {
        "id": 3,
        "title": "Squid Game",
        "genre": "Thriller",
        "year": 2021,
        "rating": "18+",
        "format": "Series",
        "seasons": 3,
        "episodes": 22,
        "imdb_rating": "8.0",
        "description": "Hundreds of contestants enter a competition where familiar childhood games have terrifying stakes.",
    },
    {
        "id": 4,
        "title": "Money Heist",
        "genre": "Crime",
        "year": 2017,
        "rating": "16+",
        "format": "Series",
        "seasons": 5,
        "episodes": 41,
        "imdb_rating": "8.2",
        "description": "A criminal mastermind brings together an unlikely crew for an ambitious heist.",
    },
    {
        "id": 5,
        "title": "Our Planet",
        "genre": "Documentary",
        "year": 2019,
        "rating": "7+",
        "format": "Series",
        "seasons": 1,
        "episodes": 8,
        "imdb_rating": "9.3",
        "description": "Discover extraordinary wildlife and the fragile natural habitats we all share.",
    },
    {
        "id": 6,
        "title": "The Queen’s Gambit",
        "genre": "Drama",
        "year": 2020,
        "rating": "16+",
        "format": "Limited series",
        "seasons": 1,
        "episodes": 7,
        "imdb_rating": "8.5",
        "description": "A gifted young chess player rises through the ranks while facing challenges beyond the board.",
    },
]
MOVIE_IDS = {movie['id'] for movie in MOVIES}
